import { useEffect, useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Home_page from "./Home/Home_page";
import { AuthContext } from "../AuthContext/Authcontext";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const { currentUser } = useContext(AuthContext);

  useEffect(() => {
    if (currentUser) {
      router.push("/");
    } else {
      router.push("/auth/signup");
    }
  }, [currentUser]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home_page />
    </div>
  );
}
