import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import Test from "../components/Test";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Test/>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hunting Coders</h1>

        <p className={styles.description}>
          A blog for hunting coders by coders
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" style={{width:"auto",height:"auto"}} width={70} height={70}/>
          </span>
        </a>
      </footer>
    </div>
  );
}
