import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomeTabs from "../components/HomeTabs";
import { BottomNavigateComponent } from "../components/Navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head> 
        <title>Project-1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <HomeTabs />
      {/* <About name={"Paras sharma"} phone={123}  /> */}
      <BottomNavigateComponent/>
    </div>

    
  );
}
