import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import About from "./about";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project-1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <About name={"Paras sharma"} />

      <h1>Home page</h1>
      <Link href="/about">Click</Link>
    </div>
  );
}
